#![feature(rustc_private)]

mod common;
use common::*;

const PROOFS: &[(&str, &str)] = &[
    (
        "001_core_slice_ChunksExact_remainder",
        include_str!("std_specs_slice_vec_proofs/cases/001_core_slice_ChunksExact_remainder.rs"),
    ),
    (
        "002_core_slice_ChunksExactMut_into_remainder",
        include_str!(
            "std_specs_slice_vec_proofs/cases/002_core_slice_ChunksExactMut_into_remainder.rs"
        ),
    ),
    (
        "006_core_slice_RChunksExact_remainder",
        include_str!("std_specs_slice_vec_proofs/cases/006_core_slice_RChunksExact_remainder.rs"),
    ),
    (
        "007_core_slice_RChunksExactMut_into_remainder",
        include_str!(
            "std_specs_slice_vec_proofs/cases/007_core_slice_RChunksExactMut_into_remainder.rs"
        ),
    ),
    (
        "010_core_slice_array_windows",
        include_str!("std_specs_slice_vec_proofs/cases/010_core_slice_array_windows.rs"),
    ),
    (
        "019_core_slice_as_mut_ptr",
        include_str!("std_specs_slice_vec_proofs/cases/019_core_slice_as_mut_ptr.rs"),
    ),
    (
        "021_core_slice_as_ptr",
        include_str!("std_specs_slice_vec_proofs/cases/021_core_slice_as_ptr.rs"),
    ),
    (
        "031_core_slice_chunk_by",
        include_str!("std_specs_slice_vec_proofs/cases/031_core_slice_chunk_by.rs"),
    ),
    (
        "032_core_slice_chunk_by_mut",
        include_str!("std_specs_slice_vec_proofs/cases/032_core_slice_chunk_by_mut.rs"),
    ),
    (
        "033_core_slice_chunks",
        include_str!("std_specs_slice_vec_proofs/cases/033_core_slice_chunks.rs"),
    ),
    (
        "034_core_slice_chunks_exact",
        include_str!("std_specs_slice_vec_proofs/cases/034_core_slice_chunks_exact.rs"),
    ),
    (
        "035_core_slice_chunks_exact_mut",
        include_str!("std_specs_slice_vec_proofs/cases/035_core_slice_chunks_exact_mut.rs"),
    ),
    (
        "036_core_slice_chunks_mut",
        include_str!("std_specs_slice_vec_proofs/cases/036_core_slice_chunks_mut.rs"),
    ),
    (
        "041_core_slice_eq_ignore_ascii_case",
        include_str!("std_specs_slice_vec_proofs/cases/041_core_slice_eq_ignore_ascii_case.rs"),
    ),
    (
        "042_core_slice_escape_ascii",
        include_str!("std_specs_slice_vec_proofs/cases/042_core_slice_escape_ascii.rs"),
    ),
    (
        "053_core_slice_get_mut",
        include_str!("std_specs_slice_vec_proofs/cases/053_core_slice_get_mut.rs"),
    ),
    (
        "060_core_slice_iter_mut",
        include_str!("std_specs_slice_vec_proofs/cases/060_core_slice_iter_mut.rs"),
    ),
    (
        "063_core_slice_make_ascii_lowercase",
        include_str!("std_specs_slice_vec_proofs/cases/063_core_slice_make_ascii_lowercase.rs"),
    ),
    (
        "064_core_slice_make_ascii_uppercase",
        include_str!("std_specs_slice_vec_proofs/cases/064_core_slice_make_ascii_uppercase.rs"),
    ),
    (
        "066_core_slice_rchunks",
        include_str!("std_specs_slice_vec_proofs/cases/066_core_slice_rchunks.rs"),
    ),
    (
        "067_core_slice_rchunks_exact",
        include_str!("std_specs_slice_vec_proofs/cases/067_core_slice_rchunks_exact.rs"),
    ),
    (
        "068_core_slice_rchunks_exact_mut",
        include_str!("std_specs_slice_vec_proofs/cases/068_core_slice_rchunks_exact_mut.rs"),
    ),
    (
        "069_core_slice_rchunks_mut",
        include_str!("std_specs_slice_vec_proofs/cases/069_core_slice_rchunks_mut.rs"),
    ),
    (
        "073_core_slice_rsplit",
        include_str!("std_specs_slice_vec_proofs/cases/073_core_slice_rsplit.rs"),
    ),
    (
        "074_core_slice_rsplit_mut",
        include_str!("std_specs_slice_vec_proofs/cases/074_core_slice_rsplit_mut.rs"),
    ),
    (
        "075_core_slice_rsplitn",
        include_str!("std_specs_slice_vec_proofs/cases/075_core_slice_rsplitn.rs"),
    ),
    (
        "076_core_slice_rsplitn_mut",
        include_str!("std_specs_slice_vec_proofs/cases/076_core_slice_rsplitn_mut.rs"),
    ),
    (
        "083_core_slice_split",
        include_str!("std_specs_slice_vec_proofs/cases/083_core_slice_split.rs"),
    ),
    (
        "088_core_slice_split_first",
        include_str!("std_specs_slice_vec_proofs/cases/088_core_slice_split_first.rs"),
    ),
    (
        "091_core_slice_split_first_mut",
        include_str!("std_specs_slice_vec_proofs/cases/091_core_slice_split_first_mut.rs"),
    ),
    (
        "092_core_slice_split_inclusive",
        include_str!("std_specs_slice_vec_proofs/cases/092_core_slice_split_inclusive.rs"),
    ),
    (
        "093_core_slice_split_inclusive_mut",
        include_str!("std_specs_slice_vec_proofs/cases/093_core_slice_split_inclusive_mut.rs"),
    ),
    (
        "094_core_slice_split_last",
        include_str!("std_specs_slice_vec_proofs/cases/094_core_slice_split_last.rs"),
    ),
    (
        "097_core_slice_split_last_mut",
        include_str!("std_specs_slice_vec_proofs/cases/097_core_slice_split_last_mut.rs"),
    ),
    (
        "098_core_slice_split_mut",
        include_str!("std_specs_slice_vec_proofs/cases/098_core_slice_split_mut.rs"),
    ),
    (
        "100_core_slice_split_off_first",
        include_str!("std_specs_slice_vec_proofs/cases/100_core_slice_split_off_first.rs"),
    ),
    (
        "101_core_slice_split_off_first_mut",
        include_str!("std_specs_slice_vec_proofs/cases/101_core_slice_split_off_first_mut.rs"),
    ),
    (
        "102_core_slice_split_off_last",
        include_str!("std_specs_slice_vec_proofs/cases/102_core_slice_split_off_last.rs"),
    ),
    (
        "103_core_slice_split_off_last_mut",
        include_str!("std_specs_slice_vec_proofs/cases/103_core_slice_split_off_last_mut.rs"),
    ),
    (
        "105_core_slice_splitn",
        include_str!("std_specs_slice_vec_proofs/cases/105_core_slice_splitn.rs"),
    ),
    (
        "106_core_slice_splitn_mut",
        include_str!("std_specs_slice_vec_proofs/cases/106_core_slice_splitn_mut.rs"),
    ),
    (
        "114_core_slice_trim_ascii",
        include_str!("std_specs_slice_vec_proofs/cases/114_core_slice_trim_ascii.rs"),
    ),
    (
        "115_core_slice_trim_ascii_end",
        include_str!("std_specs_slice_vec_proofs/cases/115_core_slice_trim_ascii_end.rs"),
    ),
    (
        "116_core_slice_trim_ascii_start",
        include_str!("std_specs_slice_vec_proofs/cases/116_core_slice_trim_ascii_start.rs"),
    ),
    (
        "117_core_slice_utf8_chunks",
        include_str!("std_specs_slice_vec_proofs/cases/117_core_slice_utf8_chunks.rs"),
    ),
    (
        "118_core_slice_windows",
        include_str!("std_specs_slice_vec_proofs/cases/118_core_slice_windows.rs"),
    ),
    (
        "124_alloc_vec_Vec_as_mut_ptr",
        include_str!("std_specs_slice_vec_proofs/cases/124_alloc_vec_Vec_as_mut_ptr.rs"),
    ),
    (
        "125_alloc_vec_Vec_as_ptr",
        include_str!("std_specs_slice_vec_proofs/cases/125_alloc_vec_Vec_as_ptr.rs"),
    ),
    (
        "134_alloc_vec_Vec_into_boxed_slice",
        include_str!("std_specs_slice_vec_proofs/cases/134_alloc_vec_Vec_into_boxed_slice.rs"),
    ),
    (
        "140_alloc_vec_Vec_resize_with",
        include_str!("std_specs_slice_vec_proofs/cases/140_alloc_vec_Vec_resize_with.rs"),
    ),
    (
        "143_alloc_vec_Vec_set_len",
        include_str!("std_specs_slice_vec_proofs/cases/143_alloc_vec_Vec_set_len.rs"),
    ),
];

#[test]
fn verify_slice_vec_implementation_proofs() {
    for (name, source) in PROOFS {
        let result = verify_files_vstd(
            name,
            [("test.rs".to_string(), source.to_string())],
            "test.rs".to_string(),
            true,
            &[],
        );
        if let Err(error) = result {
            panic!("{name} failed verification: {error:#?}");
        }
    }
}
